apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{package_name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{package_name}}
  template:
    metadata:
      labels:
        app: {{package_name}}
    spec:
      containers:
        - name: {{package_name}}
          image: {{package_name}}:local
          imagePullPolicy: IfNotPresent
