import sys; sys.path.insert(0, ".")
import numpy as np
from onnx import TensorProto
from builders.common import G

g = G()
g.init("ax_c", np.array([1], np.int64))
g.init("c5s", np.array([5],np.int64)); g.init("c5e", np.array([6],np.int64))
m5 = g.node("Slice", ["input","c5s","c5e","ax_c"], ["m5"])
Kc=np.array([[[[1,0,1],[0,0,0],[1,0,1]]]],np.float32)
Ke=np.array([[[[0,1,0],[1,0,1],[0,1,0]]]],np.float32)
g.init("Kc",Kc); g.init("Ke",Ke)
corn=g.node("Conv",[m5,"Kc"],["corn"],kernel_shape=[3,3],pads=[1,1,1,1])
edge=g.node("Conv",[m5,"Ke"],["edge"],kernel_shape=[3,3],pads=[1,1,1,1])
g.init("half",np.array(0.5,np.float32))
is5=g.node("Greater",[corn,"half"],["is5"])
ise=g.node("Greater",[edge,"half"],["ise"])
gs=g.node("ReduceSum",["input","ax_c"],["gs"],keepdims=1)
ingrid=g.node("Greater",[gs,"half"],["ingrid"])
out5b=g.node("And",[is5,ingrid],["out5b"])
not5=g.node("Not",[out5b],["not5"])
e_and=g.node("And",[ise,not5],["e_and"])
out1b=g.node("And",[e_and,ingrid],["out1b"])
out5=g.node("Cast",[out5b],["out5"],to=TensorProto.FLOAT)
out1=g.node("Cast",[out1b],["out1"],to=TensorProto.FLOAT)
any51=g.node("Or",[out5b,out1b],["any51"])
non=g.node("Not",[any51],["non"])
out0b=g.node("And",[ingrid,non],["out0b"])
out0=g.node("Cast",[out0b],["out0"],to=TensorProto.FLOAT)
g.init("zeros",np.zeros((1,1,30,30),np.float32))
g.node("Identity",["zeros"],["z"])
outs=[ (out0 if i==0 else out1 if i==1 else out5 if i==5 else "z") for i in range(10)]
g.node("Concat",outs,["output"],axis=1)
g.save("builders/task282.onnx","task282")
import os; print("282",os.path.getsize("builders/task282.onnx"))
